name: paintly_ref
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9 # Besser für Flutter als nur 'riverpod'
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # Wichtig für Flutter Init
  
  # Utilities
  uuid: ^4.2.2 # Für eindeutige IDs
  
  # Media & Interaction
  super_drag_and_drop: ^0.9.1
  photo_manager: ^3.8.3
  image_picker: ^1.0.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/Poppins-Regular.ttf
          weight: 400
